name: Auto Refresh Hugging Face Space

on:
  schedule:
    - cron: '0 10 * * *'  # 
  workflow_dispatch:       # 允许手动触发工作流

jobs:
  refresh-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restart Space via API
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          # 请修改为你的Space地址，格式为 "用户名或组织名/空间名"
          REPO_ID: "ic6/h1"
        run: |
          response=$(curl -X POST \
          -H "Authorization: Bearer $HF_TOKEN" \
          "https://huggingface.co/api/spaces/$REPO_ID/restart")
          echo "Restart API Response: $response"
